version: '3.1'


services:
  db:
    image: postgres:13.1
    privileged: true
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: django
      POSTRGES_PASSWORD: 1
      POSTGRES_DB: db1
      POSTGRES_HOST_AUTH_METHOD: trust
  backend:
    build:
      context: ./TODO
    ports:
      - 8080:8080
    command: bash -c "python manage.py migrate && python manage.py create_superuser_and-users && gunicorn TODO.wsgi -d 0.0.0.0:8080"
    depends_on:
      - db
  nginx:
    build: ./nginx
    ports:
      - 8010:80
    depends_on:
      - backend
  frontend:
    build: ./frontend
    ports:
      - 80:80
    depends_on:
      - nginx
